---

# ansible all -i hosts -m ping
# ansible-playbook -i hosts install.yaml
# ansible-playbook -i hosts install.yaml --ask-pass

- name: Local SSH
  hosts: 127.0.0.1
  
  roles:
    - local-ssh

- name: Install K3s
  hosts: all
  become: yes

  roles:
    - ssh
    - sysupdate
    - raspberry-init